apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-api
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecret }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-api
                port:
                  number: 80
